urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ayuda.views.home', name='home'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name='auth_login'),
    url(r'^register/$', 'asesor.views.register', name='auth_register'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='auth_logout'),
    
    url(r'^call/$', 'asesor.views.call', name='twilio_call'),
    url(r'^create_question/$', 'asesor.views.create_question', name='twilio_create_question'),
    url(r'^call_patient/$', 'asesor.views.call_patient', name='twilio_call_patient'),
    
    url(r'^$', 'asesor.views.about', name='about'),
    
    url(r'^dashboard/$', 'asesor.views.dashboard', name='dashboard'),
    
    url(r'^question/(?P<question_id>\d+)/$', 'asesor.views.question', name='question'),
)

asesor/forms.py
from django.contrib.auth.models import User
from django import forms
from django.utils.translation import ugettext_lazy as _

from models import USER_TYPES, Language, UserProfile

class RegistrationForm(forms.ModelForm):
    username = forms.RegexField(label=_("Username"), max_length=30, regex=r'^[\w.@+-]+$',
        help_text = _("Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only."),
        error_messages = {'invalid': _("This value may contain only letters, numbers and @/./+/-/_ characters.")})
   
    password1 = forms.CharField(label=_("Password"), widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Password confirmation"), widget=forms.PasswordInput,
        help_text = _("Enter the same password as above, for verification."))

    user_type = forms.ChoiceField(label=_("I am a"), widget=forms.RadioSelect, choices=USER_TYPES)

    languages = forms.MultipleChoiceField(label=_("I am able to translate the following to English"), required=False)

    class Meta:
        model = User
        fields = ("username", "user_type",)

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['languages'].choices = [( l.id, l.name.capitalize()) for l in Language.objects.all()]
        
    def clean_username(self):
        username = self.cleaned_data["username"]
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(_("A user with that username already exists."))

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1", "")
        password2 = self.cleaned_data["password2"]
        if password1 != password2:
            raise forms.ValidationError(_("The two password fields didn't match."))
        return password2
        
    def clean(self):
        user_type = self.cleaned_data.get("user_type")
        languages = self.cleaned_data.get("languages")
        
        if user_type == "translator" and not languages:
            self._errors["languages"] = self.error_class(["A translator must specify at least one fluent language."])
        
        return self.cleaned_data

    def save(self):
        user = super(RegistrationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.save()
        
        profile = UserProfile()
        profile.user_type = self.cleaned_data["user_type"]
        profile.user = user
        profile.save()
        
        profile.languages = Language.objects.filter(pk__in=self.cleaned_data["languages"])
        profile.save()
            
        return user
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        

templates/about.html
{% extends "base.html" %}

{% block content %}
<p style="color: gray">
   Browser Note: I've had the best luck with the HTML5 audio embed and the calling tools in Chrome. FireFox should work in theory, but
   chrome seemse to work best. As always with browsers, YMMV. 
</p>
<h3>About</h3>
<p>
    Welcome to asesor, an asynchronous medical question/translation/answer app. For more detailed information, read 
    <a href="http://blog.importrob.com/post/8607239436/asesor-a-medical-advice-app-using-django-twilio" target="_blank">the introductory blog post</a>.
    If you'd like to see the source, visit <a href="github.com">the github repo</a>.
</p>
<p>
    This is really just a proof of concept, so
    <ul>
        <li>Feel free to play around</li>
        <li>Don't expect any actual medical advice</li>
    </ul>
    
</p>
<p>
   <h3>The idea</h3>
       The basic idea is that there are many people in rural areas or 3rd world countries without ready access to simple medical advice. On the
       other hand, there are many 1st world translators and doctors who would love to volunteer their time and advice, but who are quite
       busy and can't be at the whims of cross-world timezones. 
       <br/><br/>
       Asesor is a system that brings patients, translators, and doctors together asynchronously. Patients record their question, and it 
       goes on to a queue. Translators pick questions off the queue when they have time and translate them. The translated question then
       goes into a queue for doctors to see. The doctors pick questions off the queue when they have time, and answer them. The question
       then goes back to the translator, who is responsible for calling the patient and communicating the answer in patient's language.
       <br/><br/>
       If that seems confusing, here's a quick flow-chart:<br/>
       <img src="http://media.importrob.com/asesor_flow.001.jpg">
</p>
<p>
    <h3>How it works</h3>
    Asesor has 3 parts. Asking a question, translating the question, and answering the question. 
    
    <ol>
        <li>
    <h4>Asking a Question</h4>
    To start the process, a prospective patient 
    calls into the the Asesor # assigned to their language. For the moment I've set up two numbers, one for spanish and one for german:
    <ul>
        <li>
            (415) 237-2135 - German
        </li>
        <li>
            (650) 241-4435 - Spanish
        </li>
    </ul><br/>
    The idea is that a patient lives in a rural area, speaks little or no english, and only has access to a telephone. Each question is
    tagged with a language based on the number called. This language tagging and question recording is made possible by
    <a href="http://twilio.com" target="_blank">Twilio</a>, who make telephony services super easy.
    </li>
    <li>
    <h4>Translating a Question</h4>
    The next step is a translator translates the question. If you <a href="{% url auth_register %}">create an account</a> as
    a translator, you'll see any questions that come in in your language(s). After translating, the question is sent to the doctor queue.
    </li>
    <li>
    <h4>Answering a Question</h4>
    After being translated, the question is sent to the doctor queue. If you <a href="{% url auth_register %}">create an account</a> as
    a doctor, you'll see all translated questions. Doctor's claim a question off the queue, read the translation, and enter their answer
    for the patient. After they're done, the question goes back to the translator.
    </li>
    <li>
    <h4>Calling back the Patient</h4>
    Ok maybe I lied, perhaps there are 4 parts, but this last one is really part of the translating. 
    The final step is for the translator to call the patient back and tell them the doctor's answer, 
    translating it into their native language. The translator is able to call the patient right from their browser, without ever
    knowing the patient's phone number (to protect their privacy). It also keeps translators from having to worry about paying for
    international calls. This is all made possible by the totally rad <a href="http://www.twilio.com/api/client" target="_blank">Twilio Client</a>
    which allows for in-browser calls to regular telephones.  
    </li>
    </ol>
</p>
<p>
    <h3>From here on out</h3>
    That's about it. Once again, this is just a proof of concept, so don't use it for actual medical advice. Do however play around
    with it and let me know what you think! I've put some Twilio credit into it, but calls and recordings will slowly eat into it,
    so if things seem to not be working right, I may just need to feed things some more quarters. If you have any questions or
    comments, just hit me up <a href="http://blog.importrob.com" target="_blank">on my blog</a>.
    <br/><br/>
    I'm not sure this could really become a business, but it has the kernel of what I think would be a pretty sweet non-profit. 
    The technology could certainly be improved, but there core tools are there. What's really needed is someone to put some TLC
    into gathering together some translators and doctors. That's certainly the tricky part, but there's no shortage of willingness. 
    With a dash of medical advisement and more than ~two weeks of hacking, it might be possible to get some medical advice to
    those who need it. =)
</p>

{% endblock %}

templates/base.html
<!DOCTYPE html> 
<html>

<head>
{% block script %}
<script type="text/javascript" src="{{STATIC_URL}}scripts/jquery-1.6.2.min.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}scripts/jquery-ui-1.8.14.custom.min.js"></script>
<script type="text/javascript" src="https://static.twilio.com/libs/twiliojs/1.0/twilio.min.js"></script>
{% endblock %}

{% block css %}
<link type="text/css" rel="stylesheet" href="{{STATIC_URL}}css/base.css">
<link type="text/css" rel="stylesheet" href="{{STATIC_URL}}css/redmond/jquery-ui-1.8.14.custom.css">
{% endblock %}
</head>

<body>
<div style="padding-bottom: 10px; border-bottom: 1px solid #CCC">
    <div style="font-size: 13px; float:right; font-weight: normal; color: gray;">Asynchronous, distributed medical advice</div>
    
    <h1>
        Asesor
    </h1>
    
    <a href="{% url about %}">About</a> &middot;
    <a href="{% url dashboard %}">Dashboard</a>
    {#  &middot; <a href="http://blog.importrob.com">Read the Blog Post</a> #}
    <div style="float: right">
        {% if user.is_authenticated %}
            Welcome, {{ user.username}} ({{ user.get_profile.user_type }})
            &middot;
            <a href="{% url auth_logout %}">Logout</a>
        {% else %}
            <a href="{% url auth_login %}">Login</a> &middot; <a href="{% url auth_register %}">Register</a>
        {% endif %}
    </div>
</div>

{% block content %} {% endblock %}
<div style="height: 30px"></div>
<div style="height: 20px; padding: 10px; border-top: 1px solid #CCC">
    <div style="text-align: center; font-size: 12px">&copy; 2011 Rob Boyle</div>
</div>
</body>

</html>

templates/dash_doctor.html
{% extends "base.html" %}

{% block content %}
    <h3>{{ user.get_profile.user_type|title }} Dashboard</h3>

    <div class="dash-section">
    <strong>Questions assigned to you in need of a medical answer:</strong><br/>
    {% if answer_qs %}
        <table>
            {% for question in answer_qs %}
                <tr>
                    <td>
                        <a href="{% url question question.id %}">{{ question.timestamp }}</a>
                    </td>
                    <td>
                        {{ question.language }}
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <span style="font-size: 13px; color: #666">No questions assigned to you in need of answers.</span>
    {% endif %}
    </div>
    
    <div class="dash-section">
    <strong>Unassigned questions in need of medical answers:</strong><br/>
    {% if available_qs %}        
        <table>
            {% for question in available_qs %}
                <tr>
                    <td>
                        <a href="{% url question question.id %}">{{ question.timestamp }}</a>
                    </td>
                    <td>
                        {{ question.language }}
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <span style="font-size: 13px; color: #666">No unclaimed, translated questions in need of answers.</span>    
    {% endif %}
{% endblock %}

templates/dash_translator.html
{% extends "base.html" %}

{% block content %}
    <h3>{{ user.get_profile.user_type|title }} Dashboard</h3>
    
    <div class="dash-section">
    <strong>Questions assigned to you needing a patient callback:</strong><br/>
    {% if callback_qs %} 
        <table>
            {% for question in callback_qs %}
                <tr>
                    <td>
                        <a href="{% url question question.id %}">{{ question.timestamp }}</a>
                    </td>
                    <td>
                        {{ question.language }}
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <span style="font-size: 13px; color: #666">No questions assigned to you in need of patient callbacks.</span>
    {% endif %}
    </div>
    
    <div class="dash-section">
    <strong>Questions assigned to you needing a translation:</strong><br/>
    {% if translate_qs %}      
        <table>
            {% for question in translate_qs %}
                <tr>
                    <td>
                        <a href="{% url question question.id %}">{{ question.timestamp }}</a>
                    </td>
                    <td>
                        {{ question.language }}
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <span style="font-size: 13px; color: #666">No questions assigned to you awaiting translation.</span>
    {% endif %}    
    </div>
    
    <div class="dash-section">    
    <strong>Unclaimed questions in need of translators:</strong><br/>
    {% if available_qs %}
        <table>
            <t>
            {% for question in available_qs %}
                <tr>
                    <td>
                        <a href="{% url question question.id %}">{{ question.timestamp }}</a>
                    </td>
                    <td>
                        - {{ question.language }}
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <span style="font-size: 13px; color: #666">No unclaimed questions in need of translators.</span>
    {% endif %}

{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block css %}
{{ block.super }}
<link type="text/css" rel="stylesheet" href="{{STATIC_URL}}css/auth.css">
{% endblock %}

{% block content %}
	
{% if form.errors %}
<p class="ui-state-error ui-corner-all" style="padding: 10px">Your username and password did not match our records. Please try again</p>
{% endif %}

<form method="POST" action="{% url auth_login %}">
	{% csrf_token %}
	{{form.as_p}}
	<input type="submit" value="Login"/>
</form>

{% endblock %}

templates/logout.html
{% extends "base.html" %}

{% block content %}
<h2>Thanks for stopping by!</h2>
{% endblock %}

templates/question_doctor.html
{% extends "base.html" %}

{% block content %}
    
<h3>Question - {{ question.language }} - {{ question.timestamp }}
    <span style="color: grey">(assigned to: {% if question.translator %}{{ question.translator}}{% else %}unassigned{% endif %})</span>
</h3>
<div>
    <div class="question-recording-container">
        <strong>Original Question</strong><br/>        
        <audio  controls="controls">
            <source src="{{question.recording_url}}.mp3" type="audio/mp3" />
            <source src="{{question.recording_url}}.wav" type="audio/wav" />
        </audio>    
    </div>
    <div class="question-translation-container">
        <strong>English Translation</strong><br/>
        {{ question.translation }}
    </div>
    {% if not question.doctor %}
        This question has not been assigned a doctor. Would you like to claim it?
        <form method="POST" action="{% url question question.id %}">
            {% csrf_token %}
            <input type="hidden" name="set_doctor" value='True' />
            <input type="submit" value="Claim this Question"/>
        </form>
    {% else %}
        <strong>Medical Answer</strong><br/>
        {% if not question.is_answered %}
            <form method="POST" action="{% url question question.id %}">
                {% csrf_token %}
                <textarea style="width: 600px; height: 200px; margin-bottom: 10px" name="answer">{{ question.answer }}</textarea><br/>
                <input type="checkbox" name="is_answered">Answer complete, send back to translator for a patient callback.</input>
                <div style="color:grey; font-size: 12px; padding-left: 20px">
                    Check this box when you are satisfied with your answer and wish to send it back to the original translator.<br/>
                    The translator will then contact the original patient and deliver your answer. You can save your progress<br/>
                    on an unfinished answer by clicking Save Answer without checking this box.
                </div><br/>
                <input type="submit" value="Save Answer">
            </a>
        {% else %}
            {{ question.answer }}
        {% endif %}
    {% endif %}
</div>
    
{% endblock %}

templates/question_translator.html
{% extends "base.html" %}

{% block script %}
{{ block.super }}
{% if question.is_answered and not question.is_calledback %}
<script type="text/javascript">
    $(document).ready(function() {
        $("#call-patient").button();
        $("#hangup-patient").button();
        
        Twilio.Device.setup("{{ capability_token }}");
        
        Twilio.Device.ready(function(device){
            $("#call-log").text("Ready");
        });
        
        Twilio.Device.error(function (error) {
            $("#call-log").text("Error: " + error.message);
        });
        
        Twilio.Device.connect(function (conn) {
            $("#call-log").text("Ringing...");
        });
        
        Twilio.Device.disconnect(function (conn) {
            $("#call-log").text("Call Ended");
        });
        
        $("#call-patient").click(function() {
            var params = { "question_id" : "{{ question.id }}" };
            Twilio.Device.connect(params);
                        
            return false;
        });
        
        $("#hangup-patient").click(function() {
            Twilio.Device.disconnectAll();
            
            return false;
        });
    });
</script>
{% endif %}
{% endblock %}


{% block content %}
    
<h3>Question - {{ question.language }} - {{ question.timestamp }}
    <span style="color: grey">(assigned to: {% if question.translator %}{{ question.translator}}{% else %}unassigned{% endif %})</span>
</h3>
<div>
    <div class="question-recording-container">
        <strong>Original Question</strong><br/>
        <audio  controls="controls">
            <source src="{{question.recording_url}}.mp3" type="audio/mp3" />
            <source src="{{question.recording_url}}.wave" type="audio/wav" />
        </audio>
    </div>
    {% if not question.translator %}
        This question has not been assigned a translator. Would you like to claim it?
        <form method="POST" action="{% url question question.id %}">
            {% csrf_token %}
            <input type="hidden" name="set_translator" value='True' />
            <input type="submit" value="Claim this Question"/>
        </form>
    {% else %}
        <div class="question-translation-container">
        <strong>English Translation</strong><br/>
        {% if not question.is_translated %}            
            <form method="POST" action="{% url question question.id %}">
                {% csrf_token %}
                <textarea style="width: 600px; height: 200px; margin-bottom: 10px" name="translation">{{ question.translation }}</textarea>
                <br/>
                <input type="checkbox" name="is_translated">Finished with translation, question ready for a medical opinion.</input><br/>
                <div style="color:grey; font-size: 12px; padding-left: 20px">
                    Check this box when you are satisfied with your translation and are ready to send it to a medical professional.<br/>
                    You may save your progress on an unfinished translation by clicking Save Translation without checking the box above.
                </div><br/>
                <input type="submit" value="Save Translation">
            </form>
        {% else %}
            {{ question.translation }}
        {% endif %}
        </div>
    
        {% if question.is_answered %}
            <div class="question-translation-container">
                <strong>Medical Answer</strong><br/>
                {{ question.answer }}
            </div>
        {% endif %}

        {% if question.is_answered and not question.is_calledback %}
            <div style="padding-bottom: 15px">
                <a id="call-patient" class="ui-button" href="#">Call Patient</a>
                <a id="hangup-patient" class="ui-button" href="#">Hangup</a>
                <div style="font-size: 13px">Call Status: <span id="call-log" style="font-size: 13px"></span></div>
            </div>
            <form method="POST" action="{% url question question.id %}">
                {% csrf_token %}
                <input type="checkbox" name="is_calledback">Patient successfully called back! Retire this question.</input><br/>
                <div style="color:grey; font-size: 12px; padding-left: 20px">
                    Check this box and update the question after you have successfully called the patient back and<br/>
                    given a translated version of the provided medical answer.
                </div><br/>
                <input type="submit" value="Update Question">
            </a>
        {% endif %}
    {% endif %}
</div>
    
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block css %}
{{ block.super }}
<link type="text/css" rel="stylesheet" href="{{STATIC_URL}}css/auth.css">
{% endblock %}

{% block script %}
{{ block.super }}
<script type="text/javascript">
$(document).ready(function(){
    $('label[for="id_user_type_0"]').parent().css('margin-bottom','0');
    
    $("#id_user_type_0").change(function(){
        $("label[for='id_languages']").show();
        $("#id_languages").show();
    });
    
    $("#id_user_type_1").change(function(){
        $("label[for='id_languages']").hide();
        $("#id_languages").hide();
    });
    
    $("#id_user_type_0").click();
    
    $("label[for='id_languages'], #id_languages").toggle($("#id_user_type_0").val() == 'translator');
});
</script>
{% endblock %}

{% block content %}
{% if form.errors %}
	<p style="padding: 10px" class="ui-state-error ui-corner-all">Please correct the errors below:</p>
{% endif %}

<form method="POST" action="{% url auth_register %}">
	{% csrf_token %}
	{{form.as_p}}
	
	<input type="submit" value="Create Account">
</form>

{% endblock %}